quarkus:
  http:
    port: 8000

  smallrye-openapi:
    enable: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc: # blocking
      url: jdbc:postgresql://localhost:6000/smartbar-backoffice

  hibernate-orm:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    packages: com.quarkus.smartbackoffice.persistence.entity
    database:
      generation: drop-and-create